// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/c0mp1lerworld/langlint/backend/internal/provisioner/ports/storage (interfaces: AnalyticsSourceRepository,ErrorMetricRepository,RawDataRepository,DeletionRepository)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/provisioner/ports/mocks/storage.go github.com/c0mp1lerworld/langlint/backend/internal/provisioner/ports/storage AnalyticsSourceRepository,ErrorMetricRepository,RawDataRepository,DeletionRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	analytics "github.com/c0mp1lerworld/langlint/backend/internal/domain/analytics"
	identity "github.com/c0mp1lerworld/langlint/backend/internal/domain/identity"
	storage "github.com/c0mp1lerworld/langlint/backend/internal/provisioner/ports/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsSourceRepository is a mock of AnalyticsSourceRepository interface.
type MockAnalyticsSourceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsSourceRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsSourceRepositoryMockRecorder is the mock recorder for MockAnalyticsSourceRepository.
type MockAnalyticsSourceRepositoryMockRecorder struct {
	mock *MockAnalyticsSourceRepository
}

// NewMockAnalyticsSourceRepository creates a new mock instance.
func NewMockAnalyticsSourceRepository(ctrl *gomock.Controller) *MockAnalyticsSourceRepository {
	mock := &MockAnalyticsSourceRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsSourceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsSourceRepository) EXPECT() *MockAnalyticsSourceRepositoryMockRecorder {
	return m.recorder
}

// ListCompletedAnalyses mocks base method.
func (m *MockAnalyticsSourceRepository) ListCompletedAnalyses(ctx context.Context) ([]storage.CompletedAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompletedAnalyses", ctx)
	ret0, _ := ret[0].([]storage.CompletedAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompletedAnalyses indicates an expected call of ListCompletedAnalyses.
func (mr *MockAnalyticsSourceRepositoryMockRecorder) ListCompletedAnalyses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompletedAnalyses", reflect.TypeOf((*MockAnalyticsSourceRepository)(nil).ListCompletedAnalyses), ctx)
}

// MockErrorMetricRepository is a mock of ErrorMetricRepository interface.
type MockErrorMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockErrorMetricRepositoryMockRecorder is the mock recorder for MockErrorMetricRepository.
type MockErrorMetricRepositoryMockRecorder struct {
	mock *MockErrorMetricRepository
}

// NewMockErrorMetricRepository creates a new mock instance.
func NewMockErrorMetricRepository(ctrl *gomock.Controller) *MockErrorMetricRepository {
	mock := &MockErrorMetricRepository{ctrl: ctrl}
	mock.recorder = &MockErrorMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorMetricRepository) EXPECT() *MockErrorMetricRepositoryMockRecorder {
	return m.recorder
}

// ReplaceAll mocks base method.
func (m *MockErrorMetricRepository) ReplaceAll(ctx context.Context, metrics []*analytics.ErrorMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAll", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAll indicates an expected call of ReplaceAll.
func (mr *MockErrorMetricRepositoryMockRecorder) ReplaceAll(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAll", reflect.TypeOf((*MockErrorMetricRepository)(nil).ReplaceAll), ctx, metrics)
}

// MockRawDataRepository is a mock of RawDataRepository interface.
type MockRawDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRawDataRepositoryMockRecorder
	isgomock struct{}
}

// MockRawDataRepositoryMockRecorder is the mock recorder for MockRawDataRepository.
type MockRawDataRepositoryMockRecorder struct {
	mock *MockRawDataRepository
}

// NewMockRawDataRepository creates a new mock instance.
func NewMockRawDataRepository(ctrl *gomock.Controller) *MockRawDataRepository {
	mock := &MockRawDataRepository{ctrl: ctrl}
	mock.recorder = &MockRawDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRawDataRepository) EXPECT() *MockRawDataRepositoryMockRecorder {
	return m.recorder
}

// PurgePracticesDeletedBefore mocks base method.
func (m *MockRawDataRepository) PurgePracticesDeletedBefore(ctx context.Context, cutoff time.Time) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PurgePracticesDeletedBefore", ctx, cutoff)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PurgePracticesDeletedBefore indicates an expected call of PurgePracticesDeletedBefore.
func (mr *MockRawDataRepositoryMockRecorder) PurgePracticesDeletedBefore(ctx, cutoff any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgePracticesDeletedBefore", reflect.TypeOf((*MockRawDataRepository)(nil).PurgePracticesDeletedBefore), ctx, cutoff)
}

// MockDeletionRepository is a mock of DeletionRepository interface.
type MockDeletionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeletionRepositoryMockRecorder
	isgomock struct{}
}

// MockDeletionRepositoryMockRecorder is the mock recorder for MockDeletionRepository.
type MockDeletionRepositoryMockRecorder struct {
	mock *MockDeletionRepository
}

// NewMockDeletionRepository creates a new mock instance.
func NewMockDeletionRepository(ctrl *gomock.Controller) *MockDeletionRepository {
	mock := &MockDeletionRepository{ctrl: ctrl}
	mock.recorder = &MockDeletionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletionRepository) EXPECT() *MockDeletionRepositoryMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeletionRepository) Execute(ctx context.Context, req *identity.DeletionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeletionRepositoryMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeletionRepository)(nil).Execute), ctx, req)
}

// ListPending mocks base method.
func (m *MockDeletionRepository) ListPending(ctx context.Context) ([]identity.DeletionRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", ctx)
	ret0, _ := ret[0].([]identity.DeletionRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockDeletionRepositoryMockRecorder) ListPending(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockDeletionRepository)(nil).ListPending), ctx)
}
