// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/c0mp1lerworld/langlint/backend/internal/api/ports (interfaces: LLMExtractor)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/api/ports/mocks/llm_extractor.go github.com/c0mp1lerworld/langlint/backend/internal/api/ports LLMExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/c0mp1lerworld/langlint/backend/internal/api/ports"
	analysis "github.com/c0mp1lerworld/langlint/backend/internal/domain/analysis"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMExtractor is a mock of LLMExtractor interface.
type MockLLMExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockLLMExtractorMockRecorder
	isgomock struct{}
}

// MockLLMExtractorMockRecorder is the mock recorder for MockLLMExtractor.
type MockLLMExtractorMockRecorder struct {
	mock *MockLLMExtractor
}

// NewMockLLMExtractor creates a new mock instance.
func NewMockLLMExtractor(ctrl *gomock.Controller) *MockLLMExtractor {
	mock := &MockLLMExtractor{ctrl: ctrl}
	mock.recorder = &MockLLMExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMExtractor) EXPECT() *MockLLMExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockLLMExtractor) Extract(ctx context.Context, req ports.ExtractRequest) ([]analysis.Fragment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, req)
	ret0, _ := ret[0].([]analysis.Fragment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockLLMExtractorMockRecorder) Extract(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockLLMExtractor)(nil).Extract), ctx, req)
}
