// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/c0mp1lerworld/langlint/backend/internal/api/ports/storage (interfaces: PracticeRepository,AnalysisRepository,ErrorMetricRepository,ProgressRepository,DeletionRequestRepository,AccessLogRepository,UnitOfWork,StudySessionRepository,QuizAttemptRepository)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/api/ports/mocks/storage.go github.com/c0mp1lerworld/langlint/backend/internal/api/ports/storage PracticeRepository,AnalysisRepository,ErrorMetricRepository,ProgressRepository,DeletionRequestRepository,AccessLogRepository,UnitOfWork,StudySessionRepository,QuizAttemptRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/c0mp1lerworld/langlint/backend/internal/domain"
	analysis "github.com/c0mp1lerworld/langlint/backend/internal/domain/analysis"
	analytics "github.com/c0mp1lerworld/langlint/backend/internal/domain/analytics"
	identity "github.com/c0mp1lerworld/langlint/backend/internal/domain/identity"
	practice "github.com/c0mp1lerworld/langlint/backend/internal/domain/practice"
	tutor "github.com/c0mp1lerworld/langlint/backend/internal/domain/tutor"
	gomock "go.uber.org/mock/gomock"
)

// MockPracticeRepository is a mock of PracticeRepository interface.
type MockPracticeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPracticeRepositoryMockRecorder
	isgomock struct{}
}

// MockPracticeRepositoryMockRecorder is the mock recorder for MockPracticeRepository.
type MockPracticeRepositoryMockRecorder struct {
	mock *MockPracticeRepository
}

// NewMockPracticeRepository creates a new mock instance.
func NewMockPracticeRepository(ctrl *gomock.Controller) *MockPracticeRepository {
	mock := &MockPracticeRepository{ctrl: ctrl}
	mock.recorder = &MockPracticeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPracticeRepository) EXPECT() *MockPracticeRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockPracticeRepository) GetByID(ctx context.Context, id domain.ID) (*practice.Practice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*practice.Practice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPracticeRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPracticeRepository)(nil).GetByID), ctx, id)
}

// ListAllByUser mocks base method.
func (m *MockPracticeRepository) ListAllByUser(ctx context.Context, userID domain.ID) ([]practice.Practice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllByUser", ctx, userID)
	ret0, _ := ret[0].([]practice.Practice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllByUser indicates an expected call of ListAllByUser.
func (mr *MockPracticeRepositoryMockRecorder) ListAllByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllByUser", reflect.TypeOf((*MockPracticeRepository)(nil).ListAllByUser), ctx, userID)
}

// ListByUser mocks base method.
func (m *MockPracticeRepository) ListByUser(ctx context.Context, userID domain.ID, limit, offset int) ([]practice.Practice, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]practice.Practice)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockPracticeRepositoryMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockPracticeRepository)(nil).ListByUser), ctx, userID, limit, offset)
}

// Save mocks base method.
func (m *MockPracticeRepository) Save(ctx context.Context, arg1 *practice.Practice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPracticeRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPracticeRepository)(nil).Save), ctx, arg1)
}

// MockAnalysisRepository is a mock of AnalysisRepository interface.
type MockAnalysisRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalysisRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalysisRepositoryMockRecorder is the mock recorder for MockAnalysisRepository.
type MockAnalysisRepositoryMockRecorder struct {
	mock *MockAnalysisRepository
}

// NewMockAnalysisRepository creates a new mock instance.
func NewMockAnalysisRepository(ctrl *gomock.Controller) *MockAnalysisRepository {
	mock := &MockAnalysisRepository{ctrl: ctrl}
	mock.recorder = &MockAnalysisRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalysisRepository) EXPECT() *MockAnalysisRepositoryMockRecorder {
	return m.recorder
}

// GetByPracticeID mocks base method.
func (m *MockAnalysisRepository) GetByPracticeID(ctx context.Context, practiceID domain.ID) (*analysis.Analysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPracticeID", ctx, practiceID)
	ret0, _ := ret[0].(*analysis.Analysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPracticeID indicates an expected call of GetByPracticeID.
func (mr *MockAnalysisRepositoryMockRecorder) GetByPracticeID(ctx, practiceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPracticeID", reflect.TypeOf((*MockAnalysisRepository)(nil).GetByPracticeID), ctx, practiceID)
}

// Save mocks base method.
func (m *MockAnalysisRepository) Save(ctx context.Context, arg1 *analysis.Analysis) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAnalysisRepositoryMockRecorder) Save(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAnalysisRepository)(nil).Save), ctx, arg1)
}

// MockErrorMetricRepository is a mock of ErrorMetricRepository interface.
type MockErrorMetricRepository struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMetricRepositoryMockRecorder
	isgomock struct{}
}

// MockErrorMetricRepositoryMockRecorder is the mock recorder for MockErrorMetricRepository.
type MockErrorMetricRepositoryMockRecorder struct {
	mock *MockErrorMetricRepository
}

// NewMockErrorMetricRepository creates a new mock instance.
func NewMockErrorMetricRepository(ctrl *gomock.Controller) *MockErrorMetricRepository {
	mock := &MockErrorMetricRepository{ctrl: ctrl}
	mock.recorder = &MockErrorMetricRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorMetricRepository) EXPECT() *MockErrorMetricRepositoryMockRecorder {
	return m.recorder
}

// ListByUser mocks base method.
func (m *MockErrorMetricRepository) ListByUser(ctx context.Context, userID domain.ID, window analytics.Window) ([]analytics.ErrorMetric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, window)
	ret0, _ := ret[0].([]analytics.ErrorMetric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockErrorMetricRepositoryMockRecorder) ListByUser(ctx, userID, window any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockErrorMetricRepository)(nil).ListByUser), ctx, userID, window)
}

// Upsert mocks base method.
func (m *MockErrorMetricRepository) Upsert(ctx context.Context, metric *analytics.ErrorMetric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockErrorMetricRepositoryMockRecorder) Upsert(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockErrorMetricRepository)(nil).Upsert), ctx, metric)
}

// MockProgressRepository is a mock of ProgressRepository interface.
type MockProgressRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProgressRepositoryMockRecorder
	isgomock struct{}
}

// MockProgressRepositoryMockRecorder is the mock recorder for MockProgressRepository.
type MockProgressRepositoryMockRecorder struct {
	mock *MockProgressRepository
}

// NewMockProgressRepository creates a new mock instance.
func NewMockProgressRepository(ctrl *gomock.Controller) *MockProgressRepository {
	mock := &MockProgressRepository{ctrl: ctrl}
	mock.recorder = &MockProgressRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProgressRepository) EXPECT() *MockProgressRepositoryMockRecorder {
	return m.recorder
}

// ListSamplesByUser mocks base method.
func (m *MockProgressRepository) ListSamplesByUser(ctx context.Context, userID domain.ID) ([]analytics.ProgressSample, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSamplesByUser", ctx, userID)
	ret0, _ := ret[0].([]analytics.ProgressSample)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSamplesByUser indicates an expected call of ListSamplesByUser.
func (mr *MockProgressRepositoryMockRecorder) ListSamplesByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSamplesByUser", reflect.TypeOf((*MockProgressRepository)(nil).ListSamplesByUser), ctx, userID)
}

// MockDeletionRequestRepository is a mock of DeletionRequestRepository interface.
type MockDeletionRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeletionRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockDeletionRequestRepositoryMockRecorder is the mock recorder for MockDeletionRequestRepository.
type MockDeletionRequestRepositoryMockRecorder struct {
	mock *MockDeletionRequestRepository
}

// NewMockDeletionRequestRepository creates a new mock instance.
func NewMockDeletionRequestRepository(ctrl *gomock.Controller) *MockDeletionRequestRepository {
	mock := &MockDeletionRequestRepository{ctrl: ctrl}
	mock.recorder = &MockDeletionRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletionRequestRepository) EXPECT() *MockDeletionRequestRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockDeletionRequestRepository) Append(ctx context.Context, req *identity.DeletionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockDeletionRequestRepositoryMockRecorder) Append(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockDeletionRequestRepository)(nil).Append), ctx, req)
}

// HasPending mocks base method.
func (m *MockDeletionRequestRepository) HasPending(ctx context.Context, userID domain.ID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPending", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPending indicates an expected call of HasPending.
func (mr *MockDeletionRequestRepositoryMockRecorder) HasPending(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPending", reflect.TypeOf((*MockDeletionRequestRepository)(nil).HasPending), ctx, userID)
}

// MockAccessLogRepository is a mock of AccessLogRepository interface.
type MockAccessLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccessLogRepositoryMockRecorder
	isgomock struct{}
}

// MockAccessLogRepositoryMockRecorder is the mock recorder for MockAccessLogRepository.
type MockAccessLogRepositoryMockRecorder struct {
	mock *MockAccessLogRepository
}

// NewMockAccessLogRepository creates a new mock instance.
func NewMockAccessLogRepository(ctrl *gomock.Controller) *MockAccessLogRepository {
	mock := &MockAccessLogRepository{ctrl: ctrl}
	mock.recorder = &MockAccessLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccessLogRepository) EXPECT() *MockAccessLogRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockAccessLogRepository) Append(ctx context.Context, event *identity.AccessEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockAccessLogRepositoryMockRecorder) Append(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockAccessLogRepository)(nil).Append), ctx, event)
}

// ListByUser mocks base method.
func (m *MockAccessLogRepository) ListByUser(ctx context.Context, userID domain.ID, limit, offset int) ([]identity.AccessEvent, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]identity.AccessEvent)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockAccessLogRepositoryMockRecorder) ListByUser(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockAccessLogRepository)(nil).ListByUser), ctx, userID, limit, offset)
}

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *MockUnitOfWork) InTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MockUnitOfWorkMockRecorder) InTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MockUnitOfWork)(nil).InTransaction), ctx, fn)
}

// MockStudySessionRepository is a mock of StudySessionRepository interface.
type MockStudySessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStudySessionRepositoryMockRecorder
	isgomock struct{}
}

// MockStudySessionRepositoryMockRecorder is the mock recorder for MockStudySessionRepository.
type MockStudySessionRepositoryMockRecorder struct {
	mock *MockStudySessionRepository
}

// NewMockStudySessionRepository creates a new mock instance.
func NewMockStudySessionRepository(ctrl *gomock.Controller) *MockStudySessionRepository {
	mock := &MockStudySessionRepository{ctrl: ctrl}
	mock.recorder = &MockStudySessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudySessionRepository) EXPECT() *MockStudySessionRepositoryMockRecorder {
	return m.recorder
}

// Save mocks base method.
func (m *MockStudySessionRepository) Save(ctx context.Context, session *tutor.StudySession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStudySessionRepositoryMockRecorder) Save(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStudySessionRepository)(nil).Save), ctx, session)
}

// MockQuizAttemptRepository is a mock of QuizAttemptRepository interface.
type MockQuizAttemptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuizAttemptRepositoryMockRecorder
	isgomock struct{}
}

// MockQuizAttemptRepositoryMockRecorder is the mock recorder for MockQuizAttemptRepository.
type MockQuizAttemptRepositoryMockRecorder struct {
	mock *MockQuizAttemptRepository
}

// NewMockQuizAttemptRepository creates a new mock instance.
func NewMockQuizAttemptRepository(ctrl *gomock.Controller) *MockQuizAttemptRepository {
	mock := &MockQuizAttemptRepository{ctrl: ctrl}
	mock.recorder = &MockQuizAttemptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuizAttemptRepository) EXPECT() *MockQuizAttemptRepositoryMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockQuizAttemptRepository) Append(ctx context.Context, attempt *analytics.QuizAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", ctx, attempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockQuizAttemptRepositoryMockRecorder) Append(ctx, attempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockQuizAttemptRepository)(nil).Append), ctx, attempt)
}

// ListByUser mocks base method.
func (m *MockQuizAttemptRepository) ListByUser(ctx context.Context, userID domain.ID) ([]analytics.QuizAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUser", ctx, userID)
	ret0, _ := ret[0].([]analytics.QuizAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUser indicates an expected call of ListByUser.
func (mr *MockQuizAttemptRepositoryMockRecorder) ListByUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUser", reflect.TypeOf((*MockQuizAttemptRepository)(nil).ListByUser), ctx, userID)
}
