// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/c0mp1lerworld/langlint/backend/internal/api/ports (interfaces: StudySessionGenerator)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/api/ports/mocks/study_session_generator.go github.com/c0mp1lerworld/langlint/backend/internal/api/ports StudySessionGenerator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/c0mp1lerworld/langlint/backend/internal/api/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockStudySessionGenerator is a mock of StudySessionGenerator interface.
type MockStudySessionGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockStudySessionGeneratorMockRecorder
	isgomock struct{}
}

// MockStudySessionGeneratorMockRecorder is the mock recorder for MockStudySessionGenerator.
type MockStudySessionGeneratorMockRecorder struct {
	mock *MockStudySessionGenerator
}

// NewMockStudySessionGenerator creates a new mock instance.
func NewMockStudySessionGenerator(ctrl *gomock.Controller) *MockStudySessionGenerator {
	mock := &MockStudySessionGenerator{ctrl: ctrl}
	mock.recorder = &MockStudySessionGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudySessionGenerator) EXPECT() *MockStudySessionGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockStudySessionGenerator) Generate(ctx context.Context, req ports.StudySessionRequest) (ports.StudySessionContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, req)
	ret0, _ := ret[0].(ports.StudySessionContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockStudySessionGeneratorMockRecorder) Generate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockStudySessionGenerator)(nil).Generate), ctx, req)
}
