// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/c0mp1lerworld/langlint/backend/internal/api/ports (interfaces: TutorQuestioner)
//
// Generated by this command:
//
//	mockgen -package mocks -destination internal/api/ports/mocks/tutor_questioner.go github.com/c0mp1lerworld/langlint/backend/internal/api/ports TutorQuestioner
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	ports "github.com/c0mp1lerworld/langlint/backend/internal/api/ports"
	analysis "github.com/c0mp1lerworld/langlint/backend/internal/domain/analysis"
	gomock "go.uber.org/mock/gomock"
)

// MockTutorQuestioner is a mock of TutorQuestioner interface.
type MockTutorQuestioner struct {
	ctrl     *gomock.Controller
	recorder *MockTutorQuestionerMockRecorder
	isgomock struct{}
}

// MockTutorQuestionerMockRecorder is the mock recorder for MockTutorQuestioner.
type MockTutorQuestionerMockRecorder struct {
	mock *MockTutorQuestioner
}

// NewMockTutorQuestioner creates a new mock instance.
func NewMockTutorQuestioner(ctrl *gomock.Controller) *MockTutorQuestioner {
	mock := &MockTutorQuestioner{ctrl: ctrl}
	mock.recorder = &MockTutorQuestionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTutorQuestioner) EXPECT() *MockTutorQuestionerMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockTutorQuestioner) Evaluate(ctx context.Context, req ports.EvaluateRequest) (analysis.QuizEvaluation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, req)
	ret0, _ := ret[0].(analysis.QuizEvaluation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockTutorQuestionerMockRecorder) Evaluate(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockTutorQuestioner)(nil).Evaluate), ctx, req)
}

// Question mocks base method.
func (m *MockTutorQuestioner) Question(ctx context.Context, req ports.QuestionRequest) (analysis.QuizQuestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Question", ctx, req)
	ret0, _ := ret[0].(analysis.QuizQuestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Question indicates an expected call of Question.
func (mr *MockTutorQuestionerMockRecorder) Question(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Question", reflect.TypeOf((*MockTutorQuestioner)(nil).Question), ctx, req)
}
