// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"errors"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetErrorPatternStats Agregados de patrones de error
	// (GET /analytics/error-patterns)
	GetErrorPatternStats(w http.ResponseWriter, r *http.Request, params GetErrorPatternStatsParams)
	// GetProgressSeries Serie temporal de progreso
	// (GET /analytics/progress)
	GetProgressSeries(w http.ResponseWriter, r *http.Request, params GetProgressSeriesParams)
	// GetAccessLog Auditoría de accesos del usuario
	// (GET /me/access-log)
	GetAccessLog(w http.ResponseWriter, r *http.Request, params GetAccessLogParams)
	// DeleteData Solicita el borrado de los datos del usuario
	// (DELETE /me/data)
	DeleteData(w http.ResponseWriter, r *http.Request)
	// ExportData Exporta los datos del usuario
	// (GET /me/data/export)
	ExportData(w http.ResponseWriter, r *http.Request)
	// ListPractices Lista las prácticas del usuario
	// (GET /practices)
	ListPractices(w http.ResponseWriter, r *http.Request, params ListPracticesParams)
	// CreatePractice Crea una práctica
	// (POST /practices)
	CreatePractice(w http.ResponseWriter, r *http.Request)
	// GetPractice Obtiene una práctica con su análisis embebido
	// (GET /practices/{practiceId})
	GetPractice(w http.ResponseWriter, r *http.Request, practiceId PracticeId)
	// AnalyzePractice Dispara el análisis asíncrono de una práctica
	// (POST /practices/{practiceId}/analyze)
	AnalyzePractice(w http.ResponseWriter, r *http.Request, practiceId PracticeId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetErrorPatternStats Agregados de patrones de error
// (GET /analytics/error-patterns)
func (_ Unimplemented) GetErrorPatternStats(w http.ResponseWriter, r *http.Request, params GetErrorPatternStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProgressSeries Serie temporal de progreso
// (GET /analytics/progress)
func (_ Unimplemented) GetProgressSeries(w http.ResponseWriter, r *http.Request, params GetProgressSeriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAccessLog Auditoría de accesos del usuario
// (GET /me/access-log)
func (_ Unimplemented) GetAccessLog(w http.ResponseWriter, r *http.Request, params GetAccessLogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteData Solicita el borrado de los datos del usuario
// (DELETE /me/data)
func (_ Unimplemented) DeleteData(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ExportData Exporta los datos del usuario
// (GET /me/data/export)
func (_ Unimplemented) ExportData(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListPractices Lista las prácticas del usuario
// (GET /practices)
func (_ Unimplemented) ListPractices(w http.ResponseWriter, r *http.Request, params ListPracticesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreatePractice Crea una práctica
// (POST /practices)
func (_ Unimplemented) CreatePractice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetPractice Obtiene una práctica con su análisis embebido
// (GET /practices/{practiceId})
func (_ Unimplemented) GetPractice(w http.ResponseWriter, r *http.Request, practiceId PracticeId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// AnalyzePractice Dispara el análisis asíncrono de una práctica
// (POST /practices/{practiceId}/analyze)
func (_ Unimplemented) AnalyzePractice(w http.ResponseWriter, r *http.Request, practiceId PracticeId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetErrorPatternStats operation middleware
func (siw *ServerInterfaceWrapper) GetErrorPatternStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetErrorPatternStatsParams

	// ------------- Optional query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "window", r.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "window"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "window", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetErrorPatternStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProgressSeries operation middleware
func (siw *ServerInterfaceWrapper) GetProgressSeries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetProgressSeriesParams

	// ------------- Optional query parameter "window" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "window", r.URL.Query(), &params.Window, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "window"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "window", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProgressSeries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccessLog operation middleware
func (siw *ServerInterfaceWrapper) GetAccessLog(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccessLogParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccessLog(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteData operation middleware
func (siw *ServerInterfaceWrapper) DeleteData(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportData operation middleware
func (siw *ServerInterfaceWrapper) ExportData(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportData(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPractices operation middleware
func (siw *ServerInterfaceWrapper) ListPractices(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPracticesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPractices(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePractice operation middleware
func (siw *ServerInterfaceWrapper) CreatePractice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePractice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPractice operation middleware
func (siw *ServerInterfaceWrapper) GetPractice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId PracticeId

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", chi.URLParam(r, "practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPractice(w, r, practiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AnalyzePractice operation middleware
func (siw *ServerInterfaceWrapper) AnalyzePractice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "practiceId" -------------
	var practiceId PracticeId

	err = runtime.BindStyledParameterWithOptions("simple", "practiceId", chi.URLParam(r, "practiceId"), &practiceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "practiceId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AnalyzePractice(w, r, practiceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/practices", wrapper.ListPractices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/practices", wrapper.CreatePractice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/practices/{practiceId}", wrapper.GetPractice)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/practices/{practiceId}/analyze", wrapper.AnalyzePractice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/analytics/error-patterns", wrapper.GetErrorPatternStats)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/analytics/progress", wrapper.GetProgressSeries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/data/export", wrapper.ExportData)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me/data", wrapper.DeleteData)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me/access-log", wrapper.GetAccessLog)
	})

	return r
}
