// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AnalysisStatus.
const (
	AnalysisStatusCompleted AnalysisStatus = "completed"
	AnalysisStatusFailed    AnalysisStatus = "failed"
	AnalysisStatusPending   AnalysisStatus = "pending"
)

// Valid indicates whether the value is a known member of the AnalysisStatus enum.
func (e AnalysisStatus) Valid() bool {
	switch e {
	case AnalysisStatusCompleted:
		return true
	case AnalysisStatusFailed:
		return true
	case AnalysisStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for ErrorPatternCode.
const (
	FalseFriend             ErrorPatternCode = "false_friend"
	IdiomLiteralTranslation ErrorPatternCode = "idiom_literal_translation"
	InfinitiveConjugation   ErrorPatternCode = "infinitive_conjugation"
	LexicalChoice           ErrorPatternCode = "lexical_choice"
	PassiveVoiceMisuse      ErrorPatternCode = "passive_voice_misuse"
	PrepositionInfinitive   ErrorPatternCode = "preposition_infinitive"
	PronounPossession       ErrorPatternCode = "pronoun_possession"
	TenseAgreement          ErrorPatternCode = "tense_agreement"
	WordOrder               ErrorPatternCode = "word_order"
)

// Valid indicates whether the value is a known member of the ErrorPatternCode enum.
func (e ErrorPatternCode) Valid() bool {
	switch e {
	case FalseFriend:
		return true
	case IdiomLiteralTranslation:
		return true
	case InfinitiveConjugation:
		return true
	case LexicalChoice:
		return true
	case PassiveVoiceMisuse:
		return true
	case PrepositionInfinitive:
		return true
	case PronounPossession:
		return true
	case TenseAgreement:
		return true
	case WordOrder:
		return true
	default:
		return false
	}
}

// Defines values for ErrorPatternSeverity.
const (
	Critical ErrorPatternSeverity = "critical"
	Minor    ErrorPatternSeverity = "minor"
	Moderate ErrorPatternSeverity = "moderate"
)

// Valid indicates whether the value is a known member of the ErrorPatternSeverity enum.
func (e ErrorPatternSeverity) Valid() bool {
	switch e {
	case Critical:
		return true
	case Minor:
		return true
	case Moderate:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseCode.
const (
	ErrorResponseCodeAnalysisFailed     ErrorResponseCode = "analysis_failed"
	ErrorResponseCodeAnalysisPending    ErrorResponseCode = "analysis_pending"
	ErrorResponseCodeInternal           ErrorResponseCode = "internal"
	ErrorResponseCodeInvalidState       ErrorResponseCode = "invalid_state"
	ErrorResponseCodeLlmOutputTruncated ErrorResponseCode = "llm_output_truncated"
	ErrorResponseCodeLlmUnavailable     ErrorResponseCode = "llm_unavailable"
	ErrorResponseCodeNotFound           ErrorResponseCode = "not_found"
	ErrorResponseCodeNotImplemented     ErrorResponseCode = "not_implemented"
	ErrorResponseCodeValidationError    ErrorResponseCode = "validation_error"
)

// Valid indicates whether the value is a known member of the ErrorResponseCode enum.
func (e ErrorResponseCode) Valid() bool {
	switch e {
	case ErrorResponseCodeAnalysisFailed:
		return true
	case ErrorResponseCodeAnalysisPending:
		return true
	case ErrorResponseCodeInternal:
		return true
	case ErrorResponseCodeInvalidState:
		return true
	case ErrorResponseCodeLlmOutputTruncated:
		return true
	case ErrorResponseCodeLlmUnavailable:
		return true
	case ErrorResponseCodeNotFound:
		return true
	case ErrorResponseCodeNotImplemented:
		return true
	case ErrorResponseCodeValidationError:
		return true
	default:
		return false
	}
}

// Defines values for ExerciseKind.
const (
	ExerciseKindFill ExerciseKind = "fill"
	ExerciseKindOpen ExerciseKind = "open"
)

// Valid indicates whether the value is a known member of the ExerciseKind enum.
func (e ExerciseKind) Valid() bool {
	switch e {
	case ExerciseKindFill:
		return true
	case ExerciseKindOpen:
		return true
	default:
		return false
	}
}

// Defines values for PracticeStatus.
const (
	PracticeStatusAnalyzing PracticeStatus = "analyzing"
	PracticeStatusCompleted PracticeStatus = "completed"
	PracticeStatusDraft     PracticeStatus = "draft"
	PracticeStatusFailed    PracticeStatus = "failed"
)

// Valid indicates whether the value is a known member of the PracticeStatus enum.
func (e PracticeStatus) Valid() bool {
	switch e {
	case PracticeStatusAnalyzing:
		return true
	case PracticeStatusCompleted:
		return true
	case PracticeStatusDraft:
		return true
	case PracticeStatusFailed:
		return true
	default:
		return false
	}
}

// Defines values for QuizQuestionKind.
const (
	QuizQuestionKindFill QuizQuestionKind = "fill"
	QuizQuestionKindOpen QuizQuestionKind = "open"
)

// Valid indicates whether the value is a known member of the QuizQuestionKind enum.
func (e QuizQuestionKind) Valid() bool {
	switch e {
	case QuizQuestionKindFill:
		return true
	case QuizQuestionKindOpen:
		return true
	default:
		return false
	}
}

// Defines values for StudySessionStatus.
const (
	StudySessionStatusActive    StudySessionStatus = "active"
	StudySessionStatusCompleted StudySessionStatus = "completed"
	StudySessionStatusGenerated StudySessionStatus = "generated"
)

// Valid indicates whether the value is a known member of the StudySessionStatus enum.
func (e StudySessionStatus) Valid() bool {
	switch e {
	case StudySessionStatusActive:
		return true
	case StudySessionStatusCompleted:
		return true
	case StudySessionStatusGenerated:
		return true
	default:
		return false
	}
}

// Defines values for Window.
const (
	Day   Window = "day"
	Month Window = "month"
	Week  Window = "week"
)

// Valid indicates whether the value is a known member of the Window enum.
func (e Window) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	case Week:
		return true
	default:
		return false
	}
}

// AccessLog defines model for AccessLog.
type AccessLog struct {
	Items []AccessLogEntry `json:"items"`

	// Total Número total de eventos de auditoría (sin paginar).
	Total int `json:"total"`
}

// AccessLogEntry defines model for AccessLogEntry.
type AccessLogEntry struct {
	Action       string             `json:"action"`
	Id           openapi_types.UUID `json:"id"`
	OccurredAt   time.Time          `json:"occurred_at"`
	ResourceId   *string            `json:"resource_id,omitempty"`
	ResourceType *string            `json:"resource_type,omitempty"`
}

// Analysis defines model for Analysis.
type Analysis struct {
	Fragments    []Fragment         `json:"fragments"`
	Id           openapi_types.UUID `json:"id"`
	Model        string             `json:"model"`
	ModelVersion string             `json:"model_version"`
	PracticeId   openapi_types.UUID `json:"practice_id"`
	Status       AnalysisStatus     `json:"status"`
}

// AnalysisStatus defines model for Analysis.Status.
type AnalysisStatus string

// CreatePracticeRequest defines model for CreatePracticeRequest.
type CreatePracticeRequest struct {
	// DraftText Traducción experimental del usuario (inglés).
	DraftText string `json:"draft_text"`

	// SourceText Texto base en español.
	SourceText  string       `json:"source_text"`
	TargetRules []TargetRule `json:"target_rules"`
}

// DataExport defines model for DataExport.
type DataExport struct {
	Email       openapi_types.Email `json:"email"`
	GeneratedAt time.Time           `json:"generated_at"`
	Practices   []Practice          `json:"practices"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// ErrorPattern defines model for ErrorPattern.
type ErrorPattern struct {
	// Code Taxonomía de errores (PRODUCT_DOMAIN §4.6).
	Code ErrorPatternCode `json:"code"`

	// Note Explicación breve del error.
	Note     *string              `json:"note,omitempty"`
	Severity ErrorPatternSeverity `json:"severity"`
}

// ErrorPatternAggregate defines model for ErrorPatternAggregate.
type ErrorPatternAggregate struct {
	// Code Taxonomía de errores (PRODUCT_DOMAIN §4.6).
	Code       ErrorPatternCode `json:"code"`
	Count      int              `json:"count"`
	LastSeenAt time.Time        `json:"last_seen_at"`
}

// ErrorPatternCode Taxonomía de errores (PRODUCT_DOMAIN §4.6).
type ErrorPatternCode string

// ErrorPatternSeverity defines model for ErrorPatternSeverity.
type ErrorPatternSeverity string

// ErrorPatternStats defines model for ErrorPatternStats.
type ErrorPatternStats struct {
	Patterns []ErrorPatternAggregate `json:"patterns"`
	Window   Window                  `json:"window"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    ErrorResponseCode `json:"code"`
	Message string            `json:"message"`
}

// ErrorResponseCode defines model for ErrorResponse.Code.
type ErrorResponseCode string

// ExerciseKind Tipo de ejercicio interactivo de una sesión.
type ExerciseKind string

// Fragment defines model for Fragment.
type Fragment struct {
	// Correction Corrección directa.
	Correction    string         `json:"correction"`
	ErrorPatterns []ErrorPattern `json:"error_patterns"`

	// GrammarExplanations Una o más reglas gramaticales; lista vacía si el fragmento no tiene un error gramatical que explicar.
	GrammarExplanations []GrammarExplanation `json:"grammar_explanations"`

	// LexicalClarifications Una o más aclaraciones léxicas; lista vacía si el fragmento no tiene una elección de vocabulario o colocación que aclarar.
	LexicalClarifications []LexicalClarification `json:"lexical_clarifications"`

	// SourceEs Frase base en español.
	SourceEs string `json:"source_es"`

	// TargetVerbReviews Uno o más verbos objetivo con su revisión estructurada; lista vacía si el fragmento no tiene un verbo objetivo relevante.
	TargetVerbReviews []TargetVerbReview `json:"target_verb_reviews"`

	// UserDraft Borrador del usuario (inglés).
	UserDraft string `json:"user_draft"`
}

// GrammarExplanation defines model for GrammarExplanation.
type GrammarExplanation struct {
	// Construction Cómo se construye (patrón).
	Construction string `json:"construction"`

	// Counterexample Contra-ejemplo con la frase del alumno corregida.
	Counterexample string `json:"counterexample"`

	// EsContrast Contraste con el español.
	EsContrast string `json:"es_contrast"`

	// Exception Cuándo NO aplica la regla (excepciones).
	Exception string `json:"exception"`

	// Explanation La lógica de la regla (el porqué).
	Explanation string `json:"explanation"`

	// RuleName Nombre de la regla gramatical.
	RuleName string `json:"rule_name"`
}

// LexicalClarification defines model for LexicalClarification.
type LexicalClarification struct {
	// Alternatives Alternativas admisibles y su matiz.
	Alternatives []string `json:"alternatives"`

	// Meaning Qué significa la forma correcta.
	Meaning string `json:"meaning"`

	// Term Término o expresión analizada.
	Term string `json:"term"`

	// WhyWrong Por qué la elección del alumno no encaja.
	WhyWrong string `json:"why_wrong"`
}

// Practice defines model for Practice.
type Practice struct {
	CreatedAt  time.Time          `json:"created_at"`
	DraftText  string             `json:"draft_text"`
	Id         openapi_types.UUID `json:"id"`
	SourceText string             `json:"source_text"`

	// Status Ciclo de vida de una práctica.
	Status      PracticeStatus     `json:"status"`
	TargetRules []TargetRule       `json:"target_rules"`
	UpdatedAt   time.Time          `json:"updated_at"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// PracticeDetail defines model for PracticeDetail.
type PracticeDetail struct {
	Analysis   *Analysis          `json:"analysis,omitempty"`
	CreatedAt  time.Time          `json:"created_at"`
	DraftText  string             `json:"draft_text"`
	Id         openapi_types.UUID `json:"id"`
	SourceText string             `json:"source_text"`

	// Status Ciclo de vida de una práctica.
	Status      PracticeStatus     `json:"status"`
	TargetRules []TargetRule       `json:"target_rules"`
	UpdatedAt   time.Time          `json:"updated_at"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// PracticeList defines model for PracticeList.
type PracticeList struct {
	Items []Practice `json:"items"`

	// Total Número total de prácticas del usuario (sin paginar).
	Total int `json:"total"`
}

// PracticeStatus Ciclo de vida de una práctica.
type PracticeStatus string

// ProgressPoint defines model for ProgressPoint.
type ProgressPoint struct {
	Accuracy       float32   `json:"accuracy"`
	ErrorCount     int       `json:"error_count"`
	PeriodStart    time.Time `json:"period_start"`
	TotalFragments int       `json:"total_fragments"`
}

// ProgressSeries defines model for ProgressSeries.
type ProgressSeries struct {
	Points []ProgressPoint `json:"points"`
	Window Window          `json:"window"`
}

// QuizAnswerRequest defines model for QuizAnswerRequest.
type QuizAnswerRequest struct {
	// Answer Respuesta del alumno.
	Answer string `json:"answer"`

	// FragmentIndex Índice del fragmento evaluado.
	FragmentIndex int `json:"fragment_index"`

	// Question Pregunta que se está respondiendo (devuelta por el servidor).
	Question string `json:"question"`
}

// QuizEvaluation defines model for QuizEvaluation.
type QuizEvaluation struct {
	// Correct Si la respuesta es correcta.
	Correct bool `json:"correct"`

	// Feedback Retroalimentación en español.
	Feedback string `json:"feedback"`

	// FollowUp Pregunta de seguimiento socrática; cadena vacía si no aplica.
	FollowUp string `json:"follow_up"`
}

// QuizQuestion defines model for QuizQuestion.
type QuizQuestion struct {
	// Kind Tipo de pregunta elegido por el modelo.
	Kind QuizQuestionKind `json:"kind"`

	// Prompt Enunciado de la pregunta, en español.
	Prompt string `json:"prompt"`
}

// QuizQuestionKind Tipo de pregunta elegido por el modelo.
type QuizQuestionKind string

// QuizQuestionRequest defines model for QuizQuestionRequest.
type QuizQuestionRequest struct {
	// FragmentIndex Índice del fragmento analizado sobre el que preguntar.
	FragmentIndex int `json:"fragment_index"`
}

// StudySession defines model for StudySession.
type StudySession struct {
	CreatedAt time.Time              `json:"created_at"`
	Exercises []StudySessionExercise `json:"exercises"`
	Id        openapi_types.UUID     `json:"id"`

	// Status Ciclo de vida de una sesión de estudio.
	Status StudySessionStatus `json:"status"`

	// Theory Resumen teórico en español del tema detrás de la debilidad principal.
	Theory string             `json:"theory"`
	Traps  []StudySessionTrap `json:"traps"`
	UserId openapi_types.UUID `json:"user_id"`

	// Weaknesses Puntos débiles agregados que alimentaron la sesión.
	Weaknesses []WeaknessEntry `json:"weaknesses"`
}

// StudySessionExercise defines model for StudySessionExercise.
type StudySessionExercise struct {
	Answer string `json:"answer"`

	// Kind Tipo de ejercicio interactivo de una sesión.
	Kind   ExerciseKind `json:"kind"`
	Prompt string       `json:"prompt"`
}

// StudySessionStatus Ciclo de vida de una sesión de estudio.
type StudySessionStatus string

// StudySessionTrap defines model for StudySessionTrap.
type StudySessionTrap struct {
	// Code Taxonomía de errores (PRODUCT_DOMAIN §4.6).
	Code        ErrorPatternCode `json:"code"`
	Description string           `json:"description"`
}

// TargetRule defines model for TargetRule.
type TargetRule struct {
	Note  *string `json:"note,omitempty"`
	Tense *string `json:"tense,omitempty"`
	Verb  string  `json:"verb"`
}

// TargetVerbReview defines model for TargetVerbReview.
type TargetVerbReview struct {
	// Alternatives Formas alternativas admisibles y su matiz.
	Alternatives []string `json:"alternatives"`

	// CorrectForm Forma correcta del verbo en el contexto de la frase.
	CorrectForm string `json:"correct_form"`

	// EsContrast Contraste con el español (interferencia L1).
	EsContrast string `json:"es_contrast"`

	// Rule Nombre de la regla (p. ej. "verbo + preposición fija").
	Rule string `json:"rule"`

	// Verb El verbo objetivo tal como aparece en el borrador.
	Verb string `json:"verb"`

	// Why Por qué la regla aplica a este caso.
	Why string `json:"why"`
}

// UpdatePracticeRequest defines model for UpdatePracticeRequest.
type UpdatePracticeRequest struct {
	// DraftText Traducción experimental del usuario (inglés).
	DraftText *string `json:"draft_text,omitempty"`

	// SourceText Texto base en español.
	SourceText  *string       `json:"source_text,omitempty"`
	TargetRules *[]TargetRule `json:"target_rules,omitempty"`
}

// WeaknessEntry defines model for WeaknessEntry.
type WeaknessEntry struct {
	// Code Taxonomía de errores (PRODUCT_DOMAIN §4.6).
	Code       ErrorPatternCode     `json:"code"`
	Count      int                  `json:"count"`
	LastSeenAt time.Time            `json:"last_seen_at"`
	Severity   ErrorPatternSeverity `json:"severity"`
}

// Window defines model for Window.
type Window string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// PracticeId defines model for PracticeId.
type PracticeId = openapi_types.UUID

// WindowQuery defines model for WindowQuery.
type WindowQuery = Window

// AnalysisPending defines model for AnalysisPending.
type AnalysisPending = ErrorResponse

// InvalidState defines model for InvalidState.
type InvalidState = ErrorResponse

// LLMUnavailable defines model for LLMUnavailable.
type LLMUnavailable = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ValidationError defines model for ValidationError.
type ValidationError = ErrorResponse

// GetErrorPatternStatsParams defines parameters for GetErrorPatternStats.
type GetErrorPatternStatsParams struct {
	// Window Ventana temporal de agregación (`day|week|month`). Por defecto `week`.
	Window *WindowQuery `form:"window,omitempty" json:"window,omitempty"`
}

// GetProgressSeriesParams defines parameters for GetProgressSeries.
type GetProgressSeriesParams struct {
	// Window Ventana temporal de agregación (`day|week|month`). Por defecto `week`.
	Window *WindowQuery `form:"window,omitempty" json:"window,omitempty"`
}

// GetAccessLogParams defines parameters for GetAccessLog.
type GetAccessLogParams struct {
	// Limit Número máximo de elementos por página (1..100). Por defecto `20`.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Desplazamiento desde el primer elemento. Por defecto `0`.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListPracticesParams defines parameters for ListPractices.
type ListPracticesParams struct {
	// Limit Número máximo de elementos por página (1..100). Por defecto `20`.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Desplazamiento desde el primer elemento. Por defecto `0`.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateStudySessionParams defines parameters for CreateStudySession.
type CreateStudySessionParams struct {
	// Window Ventana temporal de agregación (`day|week|month`). Por defecto `week`.
	Window *WindowQuery `form:"window,omitempty" json:"window,omitempty"`
}

// CreatePracticeJSONRequestBody defines body for CreatePractice for application/json ContentType.
type CreatePracticeJSONRequestBody = CreatePracticeRequest

// UpdatePracticeJSONRequestBody defines body for UpdatePractice for application/json ContentType.
type UpdatePracticeJSONRequestBody = UpdatePracticeRequest

// CreateQuizQuestionJSONRequestBody defines body for CreateQuizQuestion for application/json ContentType.
type CreateQuizQuestionJSONRequestBody = QuizQuestionRequest

// EvaluateQuizAnswerJSONRequestBody defines body for EvaluateQuizAnswer for application/json ContentType.
type EvaluateQuizAnswerJSONRequestBody = QuizAnswerRequest
