/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista las prácticas del usuario */
        get: operations["list_practices"];
        put?: never;
        /**
         * Crea una práctica
         * @description Registra una práctica (source + draft + reglas objetivo) en estado `draft`.
         */
        post: operations["create_practice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practices/{practiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        /** Obtiene una práctica con su análisis embebido */
        get: operations["get_practice"];
        put?: never;
        post?: never;
        /**
         * Elimina una práctica
         * @description Soft-delete: marca la práctica como eliminada; el job `purge-raw-data`
         *     del provisioner la borra físicamente después (A8, retención limitada).
         *     Bloqueado mientras `status == "analyzing"` (`409 invalid_state`).
         */
        delete: operations["delete_practice"];
        options?: never;
        head?: never;
        /**
         * Edita una práctica en borrador
         * @description Actualiza parcialmente una práctica. Solo permitido cuando
         *     `status == "draft"` (antes de analizar). Si no está en `draft`,
         *     responde `409 invalid_state`.
         */
        patch: operations["update_practice"];
        trace?: never;
    };
    "/practices/{practiceId}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dispara el análisis asíncrono de una práctica
         * @description Encola el análisis de la práctica. Responde `202` (el cliente hace
         *     polling con `GET /practices/{practiceId}`).
         *
         *     Idempotencia (AP4): si el análisis ya está en curso, responde
         *     `409 analysis_pending`, que es un ÉXITO IDEMPOTENTE. El cliente DEBE
         *     tratarlo como éxito (F5), no como error.
         */
        post: operations["analyze_practice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/error-patterns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agregados de patrones de error
         * @description Frecuencia clasificada de errores por patrón (PRODUCT_DOMAIN §7.3).
         */
        get: operations["get_error_pattern_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serie temporal de progreso
         * @description Serie temporal de precisión y volumen por ventana (PRODUCT_DOMAIN §7.1).
         */
        get: operations["get_progress_series"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exporta los datos del usuario
         * @description Portabilidad de datos (A9, GDPR Art. 15+20).
         */
        get: operations["export_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Solicita el borrado de los datos del usuario
         * @description Derecho al olvido (A9, GDPR Art. 17). El borrado no es inmediato:
         *     existe una gracia de 30 días tras la cual el job `execute-deletions`
         *     del provisioner lo materializa. Por eso responde `202`.
         */
        delete: operations["delete_data"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/access-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auditoría de accesos del usuario
         * @description Eventos append-only de auditoría (A9, A4).
         */
        get: operations["get_access_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @enum {string} */
            code: "validation_error" | "not_found" | "analysis_pending" | "analysis_failed" | "invalid_state" | "llm_unavailable";
            message: string;
        };
        CreatePracticeRequest: {
            /** @description Texto base en español. */
            source_text: string;
            /** @description Traducción experimental del usuario (inglés). */
            draft_text: string;
            target_rules: components["schemas"]["TargetRule"][];
        };
        UpdatePracticeRequest: {
            /** @description Texto base en español. */
            source_text?: string;
            /** @description Traducción experimental del usuario (inglés). */
            draft_text?: string;
            target_rules?: components["schemas"]["TargetRule"][];
        };
        TargetRule: {
            verb: string;
            tense?: string;
            note?: string;
        };
        /**
         * @description Ciclo de vida de una práctica.
         * @enum {string}
         */
        PracticeStatus: "draft" | "analyzing" | "completed" | "failed";
        Practice: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            source_text: string;
            draft_text: string;
            target_rules: components["schemas"]["TargetRule"][];
            status: components["schemas"]["PracticeStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PracticeDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            source_text: string;
            draft_text: string;
            target_rules: components["schemas"]["TargetRule"][];
            status: components["schemas"]["PracticeStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            analysis?: components["schemas"]["Analysis"] | null;
        };
        PracticeList: {
            items: components["schemas"]["Practice"][];
            /** @description Número total de prácticas del usuario (sin paginar). */
            total: number;
        };
        /**
         * @description Taxonomía de errores (PRODUCT_DOMAIN §4.6).
         * @enum {string}
         */
        ErrorPatternCode: "infinitive_conjugation" | "passive_voice_misuse" | "idiom_literal_translation" | "preposition_infinitive" | "pronoun_possession" | "false_friend" | "lexical_choice" | "word_order" | "tense_agreement";
        /** @enum {string} */
        ErrorPatternSeverity: "minor" | "moderate" | "critical";
        ErrorPattern: {
            code: components["schemas"]["ErrorPatternCode"];
            severity: components["schemas"]["ErrorPatternSeverity"];
            /** @description Explicación breve del error. */
            note?: string;
        };
        Fragment: {
            /** @description Frase base en español. */
            source_es: string;
            /** @description Borrador del usuario (inglés). */
            user_draft: string;
            /** @description Corrección directa. */
            correction: string;
            /** @description Revisión del verbo objetivo. */
            target_verb_review: string;
            /** @description Aclaración léxica. */
            lexical_clarification: string;
            /** @description Regla gramatical profunda. */
            grammar_explanation: string;
            error_patterns: components["schemas"]["ErrorPattern"][];
        };
        Analysis: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            practice_id: string;
            model: string;
            model_version: string;
            /** @enum {string} */
            status: "pending" | "completed" | "failed";
            fragments: components["schemas"]["Fragment"][];
        };
        /** @enum {string} */
        Window: "day" | "week" | "month";
        ErrorPatternStats: {
            window: components["schemas"]["Window"];
            patterns: components["schemas"]["ErrorPatternAggregate"][];
        };
        ErrorPatternAggregate: {
            code: components["schemas"]["ErrorPatternCode"];
            count: number;
            /** Format: date-time */
            last_seen_at: string;
        };
        ProgressSeries: {
            window: components["schemas"]["Window"];
            points: components["schemas"]["ProgressPoint"][];
        };
        ProgressPoint: {
            /** Format: date-time */
            period_start: string;
            total_fragments: number;
            error_count: number;
            accuracy: number;
        };
        DataExport: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            practices: components["schemas"]["Practice"][];
            /** Format: date-time */
            generated_at: string;
        };
        AccessLog: {
            items: components["schemas"]["AccessLogEntry"][];
            /** @description Número total de eventos de auditoría (sin paginar). */
            total: number;
        };
        AccessLogEntry: {
            /** Format: uuid */
            id: string;
            action: string;
            resource_type?: string;
            resource_id?: string;
            /** Format: date-time */
            occurred_at: string;
        };
    };
    responses: {
        /** @description Entrada inválida (texto vacío, reglas objetivo vacías, JSON malformado). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El recurso solicitado no existe. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Ya hay un análisis en curso para la práctica. Es un ÉXITO IDEMPOTENTE
         *     (AP4): el cliente debe tratarlo como éxito, no como error.
         */
        AnalysisPending: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description La operación no es válida para el estado actual del recurso (p. ej.
         *     editar una práctica que no está en `draft`, o borrar una que está en
         *     `analyzing`).
         */
        InvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description El proveedor LLM está caído o excedió el timeout. */
        LLMUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Identificador de la práctica (UUID v7). */
        PracticeId: string;
        /** @description Ventana temporal de agregación (`day|week|month`). Por defecto `week`. */
        WindowQuery: components["schemas"]["Window"];
        /** @description Número máximo de elementos por página (1..100). Por defecto `20`. */
        Limit: number;
        /** @description Desplazamiento desde el primer elemento. Por defecto `0`. */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_practices: {
        parameters: {
            query?: {
                /** @description Número máximo de elementos por página (1..100). Por defecto `20`. */
                limit?: components["parameters"]["Limit"];
                /** @description Desplazamiento desde el primer elemento. Por defecto `0`. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de prácticas del usuario. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeList"];
                };
            };
        };
    };
    create_practice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePracticeRequest"];
            };
        };
        responses: {
            /** @description Práctica creada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Practice"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    get_practice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Práctica con su análisis embebido (si existe). Si el análisis falló,
             *     se devuelve igualmente `200` con `analysis.status == "failed"`
             *     (no se usa `422`, reservado a errores de validación del input).
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    delete_practice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Práctica marcada como eliminada (soft-delete). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    update_practice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePracticeRequest"];
            };
        };
        responses: {
            /** @description Práctica actualizada. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Practice"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
            422: components["responses"]["ValidationError"];
        };
    };
    analyze_practice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la práctica (UUID v7). */
                practiceId: components["parameters"]["PracticeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Análisis encolado; hacer polling de `GET /practices/{practiceId}`. */
            202: {
                headers: {
                    /** @description Segundos a esperar antes de la siguiente consulta de estado. */
                    "Retry-After": number;
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["AnalysisPending"];
            503: components["responses"]["LLMUnavailable"];
        };
    };
    get_error_pattern_stats: {
        parameters: {
            query?: {
                /** @description Ventana temporal de agregación (`day|week|month`). Por defecto `week`. */
                window?: components["parameters"]["WindowQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agregados de patrones de error del usuario. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorPatternStats"];
                };
            };
        };
    };
    get_progress_series: {
        parameters: {
            query?: {
                /** @description Ventana temporal de agregación (`day|week|month`). Por defecto `week`. */
                window?: components["parameters"]["WindowQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serie temporal de progreso del usuario. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSeries"];
                };
            };
        };
    };
    export_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exportación completa de los datos del usuario. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataExport"];
                };
            };
        };
    };
    delete_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Solicitud de borrado aceptada (gracia de 30 días). */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_access_log: {
        parameters: {
            query?: {
                /** @description Número máximo de elementos por página (1..100). Por defecto `20`. */
                limit?: components["parameters"]["Limit"];
                /** @description Desplazamiento desde el primer elemento. Por defecto `0`. */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página del registro de accesos del usuario. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessLog"];
                };
            };
        };
    };
}
